import { ProductSeedInput } from "./products-sneakers";

const SHIRT_IMAGE =
  "https://res.cloudinary.com/ovwiwt64/image/upload/v1789939426/cura/media/vl8irhjorvfyn4o03ed5.jpg";
const APPAREL_CAT_IMAGE =
  "https://res.cloudinary.com/ovwiwt64/image/upload/v1789939419/cura/media/jlcvwvmt6uwyzp9ydnah.jpg";

export const SHIRTS_SEED: ProductSeedInput[] = [
  {
    sku: "SHT-001",
    slug: "cura-tailored-french-linen-shirt-raw",
    name: "Tailored French Linen Shirt Raw Parchment",
    categorySlug: "shirts",
    brandSlug: "cura-atelier",
    shortDescription: "100% Normandy French linen tailored long-sleeve shirt.",
    description: "Woven from thermoregulating Normandy flax, featuring mother-of-pearl buttons and soft spread collar.",
    basePrice: 110.0,
    compareAtPrice: 135.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Tailored French Linen Shirt", isPrimary: true, order: 1 },
      { url: APPAREL_CAT_IMAGE, alt: "Linen Shirt lifestyle detail", isPrimary: false, order: 2 },
    ],
    attributes: [
      { name: "subCategory", value: "Casual Shirts" },
      { name: "material", value: "100% French Linen" },
      { name: "fit", value: "Tailored Modern" },
      { name: "badge", value: "SALE -15%" },
    ],
    variants: [
      { sku: "SHT-001-PRC-S", sizeCode: "S", colorName: "Parchment White", price: 110.0, compareAtPrice: 135.0, inventory: 15 },
      { sku: "SHT-001-PRC-M", sizeCode: "M", colorName: "Parchment White", price: 110.0, compareAtPrice: 135.0, inventory: 18 },
      { sku: "SHT-001-PRC-L", sizeCode: "L", colorName: "Parchment White", price: 110.0, compareAtPrice: 135.0, inventory: 12, isDefault: true },
      { sku: "SHT-001-PRC-XL", sizeCode: "XL", colorName: "Parchment White", price: 110.0, compareAtPrice: 135.0, inventory: 5 },
    ],
  },
  {
    sku: "SHT-002",
    slug: "crown-thread-heavyweight-box-tee",
    name: "Heavyweight 280GSM Box Tee Charcoal",
    categorySlug: "shirts",
    brandSlug: "crown-thread",
    shortDescription: "Drop-shoulder heavyweight organic cotton graphic t-shirt.",
    description: "Crafted from combed 280GSM long-staple organic cotton for a structured boxy silhouette and high neck rib.",
    basePrice: 65.0,
    isFeatured: true,
    isNew: true,
    images: [
      { url: SHIRT_IMAGE, alt: "Heavyweight Box Tee Charcoal", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "T-Shirts" },
      { name: "material", value: "280GSM Organic Cotton" },
      { name: "fit", value: "Relaxed Boxy" },
      { name: "badge", value: "NEW DROP" },
    ],
    variants: [
      { sku: "SHT-002-CHR-M", sizeCode: "M", colorName: "Monochrome Black", price: 65.0, inventory: 25 },
      { sku: "SHT-002-CHR-L", sizeCode: "L", colorName: "Monochrome Black", price: 65.0, inventory: 20, isDefault: true },
      { sku: "SHT-002-CHR-XL", sizeCode: "XL", colorName: "Monochrome Black", price: 65.0, inventory: 14 },
    ],
  },
  {
    sku: "SHT-003",
    slug: "northline-pinpoint-oxford-navy",
    name: "Pinpoint Oxford Button-Down Deep Navy",
    categorySlug: "shirts",
    brandSlug: "northline",
    shortDescription: "Classic button-down Oxford shirt woven in sturdy cotton.",
    description: "Pre-washed 2-ply cotton Oxford cloth featuring a rolled button-down collar and curved hem.",
    basePrice: 95.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Pinpoint Oxford Deep Navy", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Formal Shirts" },
      { name: "material", value: "100% Two-Ply Cotton" },
      { name: "fit", value: "Regular Fit" },
    ],
    variants: [
      { sku: "SHT-003-NVY-M", sizeCode: "M", colorName: "Navy Blue", price: 95.0, inventory: 16 },
      { sku: "SHT-003-NVY-L", sizeCode: "L", colorName: "Navy Blue", price: 95.0, inventory: 10, isDefault: true },
    ],
  },
  {
    sku: "SHT-004",
    slug: "vertex-knit-pique-polo-olive",
    name: "Mercerized Cotton Piqué Polo Olive",
    categorySlug: "shirts",
    brandSlug: "vertex-wear",
    shortDescription: "Short-sleeve luxury mercerized cotton piqué polo.",
    description: "Refined piqué knit with a silky luster finish, mother-of-pearl placket, and ribbed collar detailing.",
    basePrice: 85.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Knit Pique Polo Olive", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polo Shirts" },
      { name: "material", value: "Mercerized Piqué Cotton" },
      { name: "fit", value: "Slim Fit" },
      { name: "badge", value: "ATELIER PICK" },
    ],
    variants: [
      { sku: "SHT-004-OLV-M", sizeCode: "M", colorName: "Olive Green", price: 85.0, inventory: 12 },
      { sku: "SHT-004-OLV-L", sizeCode: "L", colorName: "Olive Green", price: 85.0, inventory: 8, isDefault: true },
    ],
  },
  {
    sku: "SHT-005",
    slug: "aura-oversized-silk-cotton-camp-shirt",
    name: "Silk-Cotton Camp Collar Shirt Midnight",
    categorySlug: "shirts",
    brandSlug: "aura-studio",
    shortDescription: "Flowing short-sleeve resort shirt in silk and organic cotton.",
    description: "Relaxed resort silhouette featuring a flat camp collar, straight hem with side slits, and ultra-soft drape.",
    basePrice: 140.0,
    isFeatured: false,
    isNew: true,
    images: [
      { url: SHIRT_IMAGE, alt: "Camp Collar Shirt Midnight", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Oversized Shirts" },
      { name: "material", value: "30% Silk / 70% Cotton" },
      { name: "fit", value: "Oversized Resort" },
    ],
    variants: [
      { sku: "SHT-005-MID-L", sizeCode: "L", colorName: "Monochrome Black", price: 140.0, inventory: 9, isDefault: true },
    ],
  },
  {
    sku: "SHT-006",
    slug: "cura-essential-supima-crew-white",
    name: "Supima Cotton Crew Tee Pure White",
    categorySlug: "shirts",
    brandSlug: "cura-atelier",
    shortDescription: "Ultra-soft American Supima cotton everyday crewneck.",
    description: "Lightweight 180GSM extra-long staple Supima cotton t-shirt with reinforced crew neck collar.",
    basePrice: 45.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Supima Cotton Crew White", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "T-Shirts" },
      { name: "material", value: "100% Supima Cotton" },
      { name: "fit", value: "Classic Fit" },
    ],
    variants: [
      { sku: "SHT-006-WHT-S", sizeCode: "S", colorName: "Parchment White", price: 45.0, inventory: 30 },
      { sku: "SHT-006-WHT-M", sizeCode: "M", colorName: "Parchment White", price: 45.0, inventory: 25 },
      { sku: "SHT-006-WHT-L", sizeCode: "L", colorName: "Parchment White", price: 45.0, inventory: 20, isDefault: true },
    ],
  },
  {
    sku: "SHT-007",
    slug: "crown-thread-brushed-flannel-overshirt",
    name: "Brushed Heavy Flannel Overshirt Forest",
    categorySlug: "shirts",
    brandSlug: "crown-thread",
    shortDescription: "Layering overshirt woven in heavy double-brushed cotton flannel.",
    description: "Durable 340GSM cotton flannel overshirt with twin chest flap pockets and horn buttons.",
    basePrice: 125.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Brushed Heavy Flannel Overshirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Casual Shirts" },
      { name: "material", value: "100% Heavy Flannel" },
      { name: "fit", value: "Relaxed Overshirt" },
    ],
    variants: [
      { sku: "SHT-007-FRS-M", sizeCode: "M", colorName: "Olive Green", price: 125.0, inventory: 11 },
      { sku: "SHT-007-FRS-L", sizeCode: "L", colorName: "Olive Green", price: 125.0, inventory: 7, isDefault: true },
    ],
  },
  {
    sku: "SHT-008",
    slug: "aurelia-striped-poplin-shirt-blue",
    name: "Bengale Striped Italian Poplin Shirt",
    categorySlug: "shirts",
    brandSlug: "aurelia",
    shortDescription: "Crisp blue and white striped fine poplin shirt.",
    description: "Woven in Bergamo, Italy from smooth poplin yarns with single-needle tailoring and clean cuff detailing.",
    basePrice: 130.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Striped Italian Poplin Shirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Formal Shirts" },
      { name: "material", value: "Italian Cotton Poplin" },
      { name: "fit", value: "Tailored Fit" },
    ],
    variants: [
      { sku: "SHT-008-STR-L", sizeCode: "L", colorName: "Navy Blue", price: 130.0, inventory: 14, isDefault: true },
    ],
  },
  {
    sku: "SHT-009",
    slug: "northline-japanese-selvedge-denim-shirt",
    name: "10oz Japanese Selvedge Denim Shirt",
    categorySlug: "shirts",
    brandSlug: "northline",
    shortDescription: "Indigo dyed shuttle-loomed selvedge denim shirt.",
    description: "Crafted in Kojima, Japan using 10oz indigo selvedge denim that ages uniquely with wear.",
    basePrice: 155.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Japanese Selvedge Denim Shirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Casual Shirts" },
      { name: "material", value: "10oz Selvedge Denim" },
      { name: "fit", value: "Regular Fit" },
      { name: "badge", value: "TRENDING" },
    ],
    variants: [
      { sku: "SHT-009-DNM-M", sizeCode: "M", colorName: "Navy Blue", price: 155.0, inventory: 6 },
      { sku: "SHT-009-DNM-L", sizeCode: "L", colorName: "Navy Blue", price: 155.0, inventory: 4, isDefault: true },
    ],
  },
  {
    sku: "SHT-010",
    slug: "cura-graphic-archival-monolith-tee",
    name: "Archival Monolith Graphic Tee Black",
    categorySlug: "shirts",
    brandSlug: "cura-atelier",
    shortDescription: "Puff-printed archival typography street t-shirt.",
    description: "Heavyweight 240GSM cotton tee featuring high-density puff print graphic on back and micro chest logo.",
    basePrice: 55.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Archival Monolith Graphic Tee", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "T-Shirts" },
      { name: "material", value: "240GSM Cotton" },
      { name: "fit", value: "Boxy Graphic Fit" },
      { name: "badge", value: "IN-HOUSE" },
    ],
    variants: [
      { sku: "SHT-010-MON-M", sizeCode: "M", colorName: "Monochrome Black", price: 55.0, inventory: 22 },
      { sku: "SHT-010-MON-L", sizeCode: "L", colorName: "Monochrome Black", price: 55.0, inventory: 16, isDefault: true },
    ],
  },
  {
    sku: "SHT-011",
    slug: "vertex-waffle-knit-thermal-shirt",
    name: "Waffle-Knit Heavy Thermal Long-Sleeve",
    categorySlug: "shirts",
    brandSlug: "vertex-wear",
    shortDescription: "Textured honeycomb waffle cotton long-sleeve tee.",
    description: "Insulating 300GSM waffle knit cotton featuring binded cuffs and flatlock seam construction.",
    basePrice: 70.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Waffle Knit Thermal Shirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "T-Shirts" },
      { name: "material", value: "100% Waffle Cotton" },
      { name: "fit", value: "Structured Fit" },
    ],
    variants: [
      { sku: "SHT-011-WFL-L", sizeCode: "L", colorName: "Cream Oatmeal", price: 70.0, inventory: 15, isDefault: true },
    ],
  },
  {
    sku: "SHT-012",
    slug: "cura-textured-seersucker-short-sleeve",
    name: "Textured Seersucker Resort Shirt Sand",
    categorySlug: "shirts",
    brandSlug: "cura-atelier",
    shortDescription: "Pucker-textured 100% cotton summer resort shirt.",
    description: "Naturally breathable seersucker weave that lifts fabric off skin for maximum air circulation in warm climates.",
    basePrice: 90.0,
    isFeatured: false,
    isNew: true,
    images: [
      { url: SHIRT_IMAGE, alt: "Textured Seersucker Resort Shirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Oversized Shirts" },
      { name: "material", value: "100% Cotton Seersucker" },
      { name: "fit", value: "Resort Fit" },
    ],
    variants: [
      { sku: "SHT-012-SRS-M", sizeCode: "M", colorName: "Cream Oatmeal", price: 90.0, inventory: 18 },
      { sku: "SHT-012-SRS-L", sizeCode: "L", colorName: "Cream Oatmeal", price: 90.0, inventory: 12, isDefault: true },
    ],
  },
  {
    sku: "SHT-013",
    slug: "northline-merino-wool-knitted-polo",
    name: "Extra Fine Merino Wool Knitted Polo Charcoal",
    categorySlug: "shirts",
    brandSlug: "northline",
    shortDescription: "Seamless 30-gauge extra-fine Italian merino polo.",
    description: "Luxury gauge knit shirt providing lightweight insulation, natural odor resistance, and sleek silhouette.",
    basePrice: 165.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Merino Wool Knitted Polo", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polo Shirts" },
      { name: "material", value: "100% Extra Fine Merino Wool" },
      { name: "fit", value: "Modern Fit" },
    ],
    variants: [
      { sku: "SHT-013-MRN-L", sizeCode: "L", colorName: "Monochrome Black", price: 165.0, inventory: 7, isDefault: true },
    ],
  },
  {
    sku: "SHT-014",
    slug: "crown-thread-twill-utility-workshirt",
    name: "Heavy Cotton Twill Utility Workshirt Khaki",
    categorySlug: "shirts",
    brandSlug: "crown-thread",
    shortDescription: "Rugged double-pocket workshirt in durable cotton twill.",
    description: "Reinforced triple-needle stitching, metal buttons, and dual utility chest pockets built for everyday durability.",
    basePrice: 105.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Twill Utility Workshirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Casual Shirts" },
      { name: "material", value: "100% Cotton Twill" },
      { name: "fit", value: "Relaxed Workwear" },
    ],
    variants: [
      { sku: "SHT-014-TWL-M", sizeCode: "M", colorName: "Cream Oatmeal", price: 105.0, inventory: 14 },
      { sku: "SHT-014-TWL-L", sizeCode: "L", colorName: "Cream Oatmeal", price: 105.0, inventory: 9, isDefault: true },
    ],
  },
  {
    sku: "SHT-015",
    slug: "aura-studio-draped-viscose-shirt",
    name: "Fluid Viscose Resort Shirt Monolith Black",
    categorySlug: "shirts",
    brandSlug: "aura-studio",
    shortDescription: "Silk-feel draped black short-sleeve resort shirt.",
    description: "Ultra-smooth bamboo viscose fabric with matte sheen, camp collar, and hidden button placket.",
    basePrice: 115.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Fluid Viscose Resort Shirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Oversized Shirts" },
      { name: "material", value: "100% Bamboo Viscose" },
      { name: "fit", value: "Fluid Flowing" },
    ],
    variants: [
      { sku: "SHT-015-VSC-L", sizeCode: "L", colorName: "Monochrome Black", price: 115.0, inventory: 11, isDefault: true },
    ],
  },
  {
    sku: "SHT-016",
    slug: "cura-minimalist-mock-neck-tee",
    name: "Minimalist Heavy Mock Neck Tee Off-White",
    categorySlug: "shirts",
    brandSlug: "cura-atelier",
    shortDescription: "High-collar architectural tee in heavyweight jersey.",
    description: "Clean 260GSM combed jersey t-shirt with 1.5-inch fitted mock neck collar for modern layering.",
    basePrice: 60.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Minimalist Mock Neck Tee", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "T-Shirts" },
      { name: "material", value: "260GSM Jersey Cotton" },
      { name: "fit", value: "Architectural Boxy" },
    ],
    variants: [
      { sku: "SHT-016-MCK-M", sizeCode: "M", colorName: "Parchment White", price: 60.0, inventory: 17 },
      { sku: "SHT-016-MCK-L", sizeCode: "L", colorName: "Parchment White", price: 60.0, inventory: 13, isDefault: true },
    ],
  },
  {
    sku: "SHT-017",
    slug: "aurelia-sea-island-cotton-dress-shirt",
    name: "Sea Island Cotton Spread Collar Dress Shirt",
    categorySlug: "shirts",
    brandSlug: "aurelia",
    shortDescription: "Ultra-luxurious rare Sea Island long-staple cotton dress shirt.",
    description: "The pinnacle of shirting luxury, woven from 140s two-ply West Indian Sea Island cotton with hand-sewn armholes.",
    basePrice: 195.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Sea Island Cotton Dress Shirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Formal Shirts" },
      { name: "material", value: "100% Sea Island Cotton" },
      { name: "fit", value: "Bespoke Tailored" },
    ],
    variants: [
      { sku: "SHT-017-SEA-15.5", sizeCode: "M", colorName: "Parchment White", price: 195.0, inventory: 5, isDefault: true },
    ],
  },
  {
    sku: "SHT-018",
    slug: "vertex-french-terry-long-sleeve",
    name: "Loopback French Terry Long Sleeve Slate",
    categorySlug: "shirts",
    brandSlug: "vertex-wear",
    shortDescription: "Midweight loopback jersey crew long sleeve.",
    description: "320GSM unbrushed loopback cotton terry providing breathable warmth and raglan sleeve construction.",
    basePrice: 75.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Loopback French Terry Long Sleeve", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "T-Shirts" },
      { name: "material", value: "Loopback French Terry" },
      { name: "fit", value: "Athletic Fit" },
    ],
    variants: [
      { sku: "SHT-018-TRY-L", sizeCode: "L", colorName: "Slate Grey", price: 75.0, inventory: 16, isDefault: true },
    ],
  },
  {
    sku: "SHT-019",
    slug: "northline-chambray-work-shirt-blue",
    name: "Vintage Washed Cotton Chambray Shirt",
    categorySlug: "shirts",
    brandSlug: "northline",
    shortDescription: "Lightweight indigo-washed cotton chambray shirt.",
    description: "Soft pre-washed 5oz chambray fabric with contrast white stitching and cat-eye resin buttons.",
    basePrice: 88.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: SHIRT_IMAGE, alt: "Cotton Chambray Shirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Casual Shirts" },
      { name: "material", value: "100% Cotton Chambray" },
      { name: "fit", value: "Regular Fit" },
    ],
    variants: [
      { sku: "SHT-019-CHM-M", sizeCode: "M", colorName: "Navy Blue", price: 88.0, inventory: 12 },
      { sku: "SHT-019-CHM-L", sizeCode: "L", colorName: "Navy Blue", price: 88.0, inventory: 8, isDefault: true },
    ],
  },
  {
    sku: "SHT-020",
    slug: "cura-linen-cotton-band-collar-shirt",
    name: "Linen-Cotton Band Collar Grandad Shirt",
    categorySlug: "shirts",
    brandSlug: "cura-atelier",
    shortDescription: "Collarless modern grandad shirt in textured linen blend.",
    description: "Minimalist collarless design with hidden placket, curved rounded hem, and soft garment-washed finish.",
    basePrice: 98.0,
    isFeatured: true,
    isNew: true,
    images: [
      { url: SHIRT_IMAGE, alt: "Linen Cotton Band Collar Shirt", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Casual Shirts" },
      { name: "material", value: "55% Linen / 45% Cotton" },
      { name: "fit", value: "Modern Relaxed" },
      { name: "badge", value: "NEW DROP" },
    ],
    variants: [
      { sku: "SHT-020-BND-M", sizeCode: "M", colorName: "Cream Oatmeal", price: 98.0, inventory: 15 },
      { sku: "SHT-020-BND-L", sizeCode: "L", colorName: "Cream Oatmeal", price: 98.0, inventory: 10, isDefault: true },
    ],
  },
];
