import { ProductSeedInput } from "./products-sneakers";

const WATCH_IMAGE =
  "https://res.cloudinary.com/ovwiwt64/image/upload/v1789939430/cura/media/fhsosrlqavdxqwy0gppx.jpg";

export const WATCHES_SEED: ProductSeedInput[] = [
  {
    sku: "WAT-001",
    slug: "timecraft-chronograph-monolith-automatic",
    name: "Chronograph Monolith Steel Automatic 42mm",
    categorySlug: "watches",
    brandSlug: "timecraft",
    shortDescription: "Swiss automatic movement chronograph with integrated steel bracelet.",
    description: "Driven by a Valjoux 7750 mechanical self-winding calibre with 48-hour power reserve, sapphire crystal, and 100m water resistance.",
    basePrice: 420.0,
    compareAtPrice: 480.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Chronograph Monolith Steel Automatic", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Automatic Timepieces" },
      { name: "movement", value: "Swiss Valjoux 7750 Automatic" },
      { name: "caseMaterial", value: "316L Stainless Steel" },
      { name: "waterResistance", value: "100 Meters / 10 ATM" },
      { name: "badge", value: "SALE -15%" },
    ],
    variants: [
      { sku: "WAT-001-SLV-STD", sizeCode: "ONE-SIZE", colorName: "Metallic Silver", price: 420.0, compareAtPrice: 480.0, inventory: 6, isDefault: true },
    ],
  },
  {
    sku: "WAT-002",
    slug: "timecraft-diver-pro-300m-automatic",
    name: "Oceanic Diver Pro 300M Automatic Black",
    categorySlug: "watches",
    brandSlug: "timecraft",
    shortDescription: "Professional 300m diver watch with matte ceramic bezel.",
    description: "High-grade 300-meter professional diving watch with 120-click unidirectional ceramic bezel and Swiss Super-LumiNova BGW9 indices.",
    basePrice: 380.0,
    isFeatured: true,
    isNew: true,
    images: [
      { url: WATCH_IMAGE, alt: "Oceanic Diver Pro 300M", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Sport & Diver Watches" },
      { name: "movement", value: "Japanese Seiko NH35 Automatic" },
      { name: "caseMaterial", value: "316L Steel & Ceramic Bezel" },
      { name: "waterResistance", value: "300 Meters / 30 ATM" },
      { name: "badge", value: "NEW DROP" },
    ],
    variants: [
      { sku: "WAT-002-BLK-STD", sizeCode: "ONE-SIZE", colorName: "Monochrome Black", price: 380.0, inventory: 8, isDefault: true },
    ],
  },
  {
    sku: "WAT-003",
    slug: "cura-minimalist-quartz-38mm-rose-gold",
    name: "Atelier Minimalist Quartz 38mm Rose Gold",
    categorySlug: "watches",
    brandSlug: "cura-atelier",
    shortDescription: "Ultra-slim 6mm quartz watch with Italian leather strap.",
    description: "Sleek architectural dress timepiece with sandblasted rose gold case, domed mineral crystal, and quick-release Horween leather band.",
    basePrice: 195.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Atelier Minimalist Quartz Rose Gold", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Minimalist Quartz" },
      { name: "movement", value: "Japanese Miyota 2025 Quartz" },
      { name: "caseMaterial", value: "Rose Gold PVD Steel" },
      { name: "waterResistance", value: "50 Meters / 5 ATM" },
      { name: "badge", value: "ATELIER PICK" },
    ],
    variants: [
      { sku: "WAT-003-RSG-STD", sizeCode: "ONE-SIZE", colorName: "Rose Gold", price: 195.0, inventory: 15, isDefault: true },
    ],
  },
  {
    sku: "WAT-004",
    slug: "aura-studio-stealth-blackout-tactical",
    name: "Stealth Blackout Tactical Quartz 40mm",
    categorySlug: "watches",
    brandSlug: "aura-studio",
    shortDescription: "Full matte black DLC coated military field watch.",
    description: "Diamond-Like Carbon (DLC) hardened case with anti-reflective sapphire crystal, black dial, and Cordura ballistic nylon strap.",
    basePrice: 240.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Stealth Blackout Tactical Quartz", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Sport & Diver Watches" },
      { name: "movement", value: "High-Torque Quartz" },
      { name: "caseMaterial", value: "Matte Black DLC Steel" },
      { name: "badge", value: "TRENDING" },
    ],
    variants: [
      { sku: "WAT-004-BLK-STD", sizeCode: "ONE-SIZE", colorName: "Matte Black", price: 240.0, inventory: 10, isDefault: true },
    ],
  },
  {
    sku: "WAT-005",
    slug: "timecraft-heritage-small-seconds-automatic",
    name: "Heritage Small-Seconds Dress Watch 39mm",
    categorySlug: "watches",
    brandSlug: "timecraft",
    shortDescription: "Vintage-inspired automatic watch with sunray dial.",
    description: "Features a sub-dial small seconds complication at 6 o'clock, polished dauphine hands, and alligator grain leather strap.",
    basePrice: 350.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Heritage Small-Seconds Dress Watch", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Luxury Chronographs" },
      { name: "movement", value: "Automatic Mechanical" },
      { name: "caseMaterial", value: "Polished Stainless Steel" },
    ],
    variants: [
      { sku: "WAT-005-SLV-STD", sizeCode: "ONE-SIZE", colorName: "Metallic Silver", price: 350.0, inventory: 4, isDefault: true },
    ],
  },
  {
    sku: "WAT-006",
    slug: "cura-titanium-field-automatic-40mm",
    name: "Grade 2 Titanium Field Automatic 40mm",
    categorySlug: "watches",
    brandSlug: "cura-atelier",
    shortDescription: "Featherlight titanium field watch with 24h dial.",
    description: "Ultra-durable, hypoallergenic Grade 2 titanium construction weighing only 52 grams on a heavy canvas NATO strap.",
    basePrice: 280.0,
    isFeatured: false,
    isNew: true,
    images: [
      { url: WATCH_IMAGE, alt: "Grade 2 Titanium Field Automatic", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Automatic Timepieces" },
      { name: "movement", value: "Japanese Automatic" },
      { name: "caseMaterial", value: "Grade 2 Titanium" },
      { name: "badge", value: "IN-HOUSE" },
    ],
    variants: [
      { sku: "WAT-006-TTN-STD", sizeCode: "ONE-SIZE", colorName: "Slate Grey", price: 280.0, inventory: 12, isDefault: true },
    ],
  },
  {
    sku: "WAT-007",
    slug: "aura-studio-square-monolith-digital",
    name: "Square Monolith Steel Digital Watch",
    categorySlug: "watches",
    brandSlug: "aura-studio",
    shortDescription: "Architectural retro-futuristic steel digital watch.",
    description: "Solid stainless steel case housing an inverted black LCD display with EL backlight and integrated 5-link bracelet.",
    basePrice: 160.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Square Monolith Steel Digital", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Minimalist Quartz" },
      { name: "movement", value: "Custom Digital Module" },
      { name: "caseMaterial", value: "Brushed Steel" },
    ],
    variants: [
      { sku: "WAT-007-SLV-STD", sizeCode: "ONE-SIZE", colorName: "Metallic Silver", price: 160.0, inventory: 18, isDefault: true },
    ],
  },
  {
    sku: "WAT-008",
    slug: "timecraft-gmt-worldtimer-automatic-41mm",
    name: "GMT Worldtimer Automatic Pepsi Bezel",
    categorySlug: "watches",
    brandSlug: "timecraft",
    shortDescription: "Dual time-zone GMT automatic with red/blue bezel.",
    description: "Track two time zones simultaneously with an independent GMT hand and 24-hour bi-directional 24-stop bezel.",
    basePrice: 450.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "GMT Worldtimer Automatic", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Luxury Chronographs" },
      { name: "movement", value: "Swiss GMT Automatic" },
      { name: "caseMaterial", value: "316L Stainless Steel" },
    ],
    variants: [
      { sku: "WAT-008-GMT-STD", sizeCode: "ONE-SIZE", colorName: "Navy Blue", price: 450.0, inventory: 5, isDefault: true },
    ],
  },
  {
    sku: "WAT-009",
    slug: "cura-mesh-bracelet-quartz-black-dial",
    name: "Milanese Mesh Quartz Black Dial 40mm",
    categorySlug: "watches",
    brandSlug: "cura-atelier",
    shortDescription: "Sleek stainless steel watch with fine Milanese mesh strap.",
    description: "Ultra-thin stainless steel watch featuring a sunray black dial, polished indices, and magnetic clasp mesh bracelet.",
    basePrice: 175.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Milanese Mesh Quartz", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Minimalist Quartz" },
      { name: "movement", value: "Miyota Slim Quartz" },
      { name: "caseMaterial", value: "316L Stainless Steel" },
    ],
    variants: [
      { sku: "WAT-009-MSH-STD", sizeCode: "ONE-SIZE", colorName: "Monochrome Black", price: 175.0, inventory: 14, isDefault: true },
    ],
  },
  {
    sku: "WAT-010",
    slug: "timecraft-skeleton-automatic-exhibition-case",
    name: "Skeleton Automatic Exhibition Back 42mm",
    categorySlug: "watches",
    brandSlug: "timecraft",
    shortDescription: "Fully openworked mechanical skeleton movement.",
    description: "Showcasing intricate gear work and balance wheel oscillations through sapphire front and rear exhibition crystal.",
    basePrice: 490.0,
    isFeatured: false,
    isNew: true,
    images: [
      { url: WATCH_IMAGE, alt: "Skeleton Automatic Exhibition Back", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Automatic Timepieces" },
      { name: "movement", value: "Custom Skeleton Automatic" },
      { name: "caseMaterial", value: "Polished Steel" },
    ],
    variants: [
      { sku: "WAT-010-SKL-STD", sizeCode: "ONE-SIZE", colorName: "Metallic Silver", price: 490.0, inventory: 3, isDefault: true },
    ],
  },
  {
    sku: "WAT-011",
    slug: "aura-pilot-flieger-automatic-43mm",
    name: "Aura Flieger Type-A Pilot Watch 43mm",
    categorySlug: "watches",
    brandSlug: "aura-studio",
    shortDescription: "High-readability vintage pilot watch with onion crown.",
    description: "Large 43mm bead-blasted case, high-contrast luminescent Type-A dial layout, and riveted pilot leather strap.",
    basePrice: 310.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Aura Flieger Type-A Pilot Watch", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Sport & Diver Watches" },
      { name: "movement", value: "Automatic Mechanical" },
      { name: "caseMaterial", value: "Bead-Blasted Steel" },
    ],
    variants: [
      { sku: "WAT-011-FLG-STD", sizeCode: "ONE-SIZE", colorName: "Monochrome Black", price: 310.0, inventory: 9, isDefault: true },
    ],
  },
  {
    sku: "WAT-012",
    slug: "cura-vintage-cushion-case-automatic-gold",
    name: "Vintage Cushion Case Automatic Champagne Gold",
    categorySlug: "watches",
    brandSlug: "cura-atelier",
    shortDescription: "70s retro cushion-shaped case dress automatic.",
    description: "Sculpted TV-cushion case geometry with warm champagne brushed dial and integrated solid steel bracelet.",
    basePrice: 295.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Vintage Cushion Case Automatic", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Automatic Timepieces" },
      { name: "movement", value: "Japanese Automatic" },
      { name: "caseMaterial", value: "Gold PVD Steel" },
    ],
    variants: [
      { sku: "WAT-012-CSH-STD", sizeCode: "ONE-SIZE", colorName: "Rose Gold", price: 295.0, inventory: 7, isDefault: true },
    ],
  },
  {
    sku: "WAT-013",
    slug: "timecraft-compressor-diver-dual-crown",
    name: "Super Compressor Dual-Crown Diver 200M",
    categorySlug: "watches",
    brandSlug: "timecraft",
    shortDescription: "Internal rotating bezel dual-crown compressor diver.",
    description: "Classic twin-crown architecture with cross-hatched crowns operating an internal rotating timing ring.",
    basePrice: 375.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Super Compressor Dual-Crown Diver", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Sport & Diver Watches" },
      { name: "movement", value: "Swiss Sellita SW200" },
      { name: "caseMaterial", value: "316L Stainless Steel" },
    ],
    variants: [
      { sku: "WAT-013-CMP-STD", sizeCode: "ONE-SIZE", colorName: "Navy Blue", price: 375.0, inventory: 6, isDefault: true },
    ],
  },
  {
    sku: "WAT-014",
    slug: "aura-monochrome-ceramic-quartz-black",
    name: "Full Black Matte Ceramic Quartz 41mm",
    categorySlug: "watches",
    brandSlug: "aura-studio",
    shortDescription: "Scratch-proof matte black high-tech ceramic timepiece.",
    description: "Constructed entirely from ultra-hard zirconium oxide ceramic with sapphire crystal and ceramic link bracelet.",
    basePrice: 360.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Full Black Matte Ceramic Quartz", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Minimalist Quartz" },
      { name: "movement", value: "Precision Swiss Quartz" },
      { name: "caseMaterial", value: "ZrO2 High-Tech Ceramic" },
    ],
    variants: [
      { sku: "WAT-014-CRM-STD", sizeCode: "ONE-SIZE", colorName: "Monochrome Black", price: 360.0, inventory: 8, isDefault: true },
    ],
  },
  {
    sku: "WAT-015",
    slug: "cura-regatta-timer-quartz-chronograph",
    name: "Regatta Yachting Timer Quartz Chronograph",
    categorySlug: "watches",
    brandSlug: "cura-atelier",
    shortDescription: "Marine countdown yachting timer with rubber strap.",
    description: "5-minute sailing countdown function, tachymeter scale, and durable vulcanized FKM rubber strap.",
    basePrice: 220.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Regatta Yachting Timer Chronograph", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Luxury Chronographs" },
      { name: "movement", value: "Meca-Quartz Chronograph" },
      { name: "caseMaterial", value: "Stainless Steel" },
    ],
    variants: [
      { sku: "WAT-015-RGT-STD", sizeCode: "ONE-SIZE", colorName: "Navy Blue", price: 220.0, inventory: 11, isDefault: true },
    ],
  },
  {
    sku: "WAT-016",
    slug: "timecraft-moonphase-calendar-automatic",
    name: "Master Moonphase Complete Calendar 40mm",
    categorySlug: "watches",
    brandSlug: "timecraft",
    shortDescription: "Complex calendar watch displaying moon phase, day, and month.",
    description: "Features realistic gold foil moonphase indicator sub-dial, pointer date hand, and day/month windows.",
    basePrice: 520.0,
    isFeatured: true,
    isNew: true,
    images: [
      { url: WATCH_IMAGE, alt: "Master Moonphase Complete Calendar", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Luxury Chronographs" },
      { name: "movement", value: "Swiss Automatic Calendar" },
      { name: "caseMaterial", value: "Polished Steel" },
      { name: "badge", value: "NEW DROP" },
    ],
    variants: [
      { sku: "WAT-016-MNP-STD", sizeCode: "ONE-SIZE", colorName: "Metallic Silver", price: 520.0, inventory: 2, isDefault: true },
    ],
  },
  {
    sku: "WAT-017",
    slug: "aura-tactical-solar-powered-watch",
    name: "Solar-Powered Outdoor Utility Watch 42mm",
    categorySlug: "watches",
    brandSlug: "aura-studio",
    shortDescription: "Solar charging dial requiring zero battery replacements.",
    description: "Converts any light source into electrical energy stored in a rechargeable cell with 6-month power reserve.",
    basePrice: 210.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Solar-Powered Outdoor Utility Watch", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Sport & Diver Watches" },
      { name: "movement", value: "Solar Quartz Movement" },
      { name: "caseMaterial", value: "Reinforced Composite" },
    ],
    variants: [
      { sku: "WAT-017-SLR-STD", sizeCode: "ONE-SIZE", colorName: "Olive Green", price: 210.0, inventory: 15, isDefault: true },
    ],
  },
  {
    sku: "WAT-018",
    slug: "cura-minimalist-two-hand-quartz-slate",
    name: "Atelier Two-Hand Ultra Thin Slate 36mm",
    categorySlug: "watches",
    brandSlug: "cura-atelier",
    shortDescription: "Mid-size 36mm minimalist watch with grey sunray dial.",
    description: "Designed with clean proportion, 5mm slim profile, scratch-resistant sapphire crystal, and grey suede strap.",
    basePrice: 180.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "Atelier Two-Hand Ultra Thin Slate", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Minimalist Quartz" },
      { name: "movement", value: "Miyota Two-Hand Quartz" },
      { name: "caseMaterial", value: "316L Stainless Steel" },
    ],
    variants: [
      { sku: "WAT-018-SLT-STD", sizeCode: "ONE-SIZE", colorName: "Slate Grey", price: 180.0, inventory: 12, isDefault: true },
    ],
  },
  {
    sku: "WAT-019",
    slug: "timecraft-bronze-patina-diver-42mm",
    name: "CuSn8 Bronze Patina Diver 300M 42mm",
    categorySlug: "watches",
    brandSlug: "timecraft",
    shortDescription: "Solid CuSn8 marine bronze watch that develops unique patina.",
    description: "Constructed from real marine-grade bronze alloy that oxidizes individually over time based on owner environment.",
    basePrice: 410.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: WATCH_IMAGE, alt: "CuSn8 Bronze Patina Diver", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Sport & Diver Watches" },
      { name: "movement", value: "Automatic Mechanical" },
      { name: "caseMaterial", value: "CuSn8 Marine Bronze" },
    ],
    variants: [
      { sku: "WAT-019-BNZ-STD", sizeCode: "ONE-SIZE", colorName: "Tortoise Amber", price: 410.0, inventory: 4, isDefault: true },
    ],
  },
  {
    sku: "WAT-020",
    slug: "cura-racing-meca-quartz-chronograph",
    name: "Heritage 1970 Racing Meca-Quartz Chronograph",
    categorySlug: "watches",
    brandSlug: "cura-atelier",
    shortDescription: "Bicompax racing chronograph with instant flywheel reset.",
    description: "Combines battery quartz timekeeping accuracy with mechanical chronograph hand sweep and tactile button feel.",
    basePrice: 250.0,
    isFeatured: true,
    isNew: true,
    images: [
      { url: WATCH_IMAGE, alt: "Heritage 1970 Racing Meca-Quartz", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Luxury Chronographs" },
      { name: "movement", value: "Seiko VK64 Meca-Quartz" },
      { name: "caseMaterial", value: "Brushed Steel" },
      { name: "badge", value: "IN-HOUSE" },
    ],
    variants: [
      { sku: "WAT-020-RCE-STD", sizeCode: "ONE-SIZE", colorName: "Monochrome Black", price: 250.0, inventory: 10, isDefault: true },
    ],
  },
];
