import { ProductSeedInput } from "./products-sneakers";

const EYEWEAR_IMAGE =
  "https://res.cloudinary.com/ovwiwt64/image/upload/v1789939421/cura/media/ttmav1ptoigprqbeprlv.jpg";

export const SPECTACLES_SEED: ProductSeedInput[] = [
  {
    sku: "SPC-001",
    slug: "cura-optics-polarized-acetate-solar-tortoise",
    name: "Acetate Solar Frames Polarized Tortoise",
    categorySlug: "spectacles",
    brandSlug: "visionary-frames",
    shortDescription: "Hand-polished Italian Mazzucchelli acetate polarized sunglasses.",
    description: "Features premium 100% UV400 polarized mineral glass lenses, 5-barrel German hinges, and bevelled edge profiles.",
    basePrice: 145.0,
    compareAtPrice: 175.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Acetate Solar Frames Tortoise", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "Mazzucchelli Acetate" },
      { name: "lensType", value: "Polarized UV400 Mineral Glass" },
      { name: "badge", value: "SALE -15%" },
    ],
    variants: [
      { sku: "SPC-001-TRT-STD", sizeCode: "STD", colorName: "Tortoise Amber", price: 145.0, compareAtPrice: 175.0, inventory: 15, isDefault: true },
      { sku: "SPC-001-TRT-WIDE", sizeCode: "WIDE", colorName: "Tortoise Amber", price: 145.0, compareAtPrice: 175.0, inventory: 8 },
    ],
  },
  {
    sku: "SPC-002",
    slug: "moscot-studio-lemtosh-optical-wire",
    name: "Lemtosh Optical Wire Frame Antique Gold",
    categorySlug: "spectacles",
    brandSlug: "moscot-studio",
    shortDescription: "Heritage round-square optical frame with keyhole bridge.",
    description: "Classic New York mid-century optical silhouette featuring diamond rivets and hypoallergenic titanium nose pads.",
    basePrice: 210.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Lemtosh Optical Wire Frame", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Optical Frames" },
      { name: "frameMaterial", value: "Custom Acetate & Metal" },
      { name: "badge", value: "ATELIER PICK" },
    ],
    variants: [
      { sku: "SPC-002-GLD-STD", sizeCode: "STD", colorName: "Tortoise Amber", price: 210.0, inventory: 10, isDefault: true },
    ],
  },
  {
    sku: "SPC-003",
    slug: "oliver-peoples-gregory-peck-crystal",
    name: "Gregory Peck Crystal Clear Frames",
    categorySlug: "spectacles",
    brandSlug: "oliver-peoples",
    shortDescription: "Iconic clear crystal acetate round optical spectacles.",
    description: "Designed in collaboration with the Peck Estate, featuring translucent hand-crafted crystal acetate and embedded core wire.",
    basePrice: 320.0,
    isFeatured: true,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Gregory Peck Crystal Clear", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Optical Frames" },
      { name: "frameMaterial", value: "Translucent Crystal Acetate" },
      { name: "badge", value: "TRENDING" },
    ],
    variants: [
      { sku: "SPC-003-CRY-STD", sizeCode: "STD", colorName: "Crystal Clear", price: 320.0, inventory: 5, isDefault: true },
    ],
  },
  {
    sku: "SPC-004",
    slug: "cura-titanium-round-wire-blue-light",
    name: "Titanium Round Wire Anti-Blue Light Glasses",
    categorySlug: "spectacles",
    brandSlug: "visionary-frames",
    shortDescription: "Featherlight Japanese titanium computer screen glasses.",
    description: "Weighing only 11 grams, featuring precision blue-light filtering CR-39 lenses that eliminate digital eye strain.",
    basePrice: 165.0,
    isFeatured: false,
    isNew: true,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Titanium Round Wire Anti-Blue Light", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Anti-Blue Light" },
      { name: "frameMaterial", value: "Japanese Beta Titanium" },
      { name: "lensType", value: "Anti-Reflective Blue-Blocker" },
      { name: "badge", value: "NEW DROP" },
    ],
    variants: [
      { sku: "SPC-004-TTN-STD", sizeCode: "STD", colorName: "Metallic Silver", price: 165.0, inventory: 20, isDefault: true },
    ],
  },
  {
    sku: "SPC-005",
    slug: "visionary-wayfarer-bold-black-polarized",
    name: "Bold Wayfarer Polarized Jet Black",
    categorySlug: "spectacles",
    brandSlug: "visionary-frames",
    shortDescription: "Thick 8mm sculpted black acetate wayfarer sunglasses.",
    description: "Statement thick-profile acetate geometry with G-15 green polarized lenses and custom filigree core wire.",
    basePrice: 185.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Bold Wayfarer Polarized Jet Black", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "8mm Heavy Duty Acetate" },
    ],
    variants: [
      { sku: "SPC-005-BLK-STD", sizeCode: "STD", colorName: "Matte Black", price: 185.0, inventory: 12, isDefault: true },
    ],
  },
  {
    sku: "SPC-006",
    slug: "cura-aviator-teardrop-metal-gold",
    name: "Teardrop Aviator Double-Bridge Solar Gold",
    categorySlug: "spectacles",
    brandSlug: "cura-atelier",
    shortDescription: "Classic pilot double-bridge metal aviator sunglasses.",
    description: "Ultra-thin stainless steel wire frame with teardrop gradient lenses, silicone nose pads, and acetate temple tips.",
    basePrice: 135.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Teardrop Aviator Double-Bridge Gold", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "Stainless Steel Wire" },
      { name: "badge", value: "IN-HOUSE" },
    ],
    variants: [
      { sku: "SPC-006-AVT-STD", sizeCode: "STD", colorName: "Rose Gold", price: 135.0, inventory: 18, isDefault: true },
    ],
  },
  {
    sku: "SPC-007",
    slug: "moscot-sqaure-thick-acetate-optical",
    name: "Square Architectural Acetate Optical Black",
    categorySlug: "spectacles",
    brandSlug: "moscot-studio",
    shortDescription: "Bold architectural square frame for prescription lenses.",
    description: "Substantial square optical frame engineered with keyhole bridge and paddle temples for secure fit.",
    basePrice: 225.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Square Architectural Acetate Optical", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Optical Frames" },
      { name: "frameMaterial", value: "High-Density Acetate" },
    ],
    variants: [
      { sku: "SPC-007-SQR-STD", sizeCode: "STD", colorName: "Monochrome Black", price: 225.0, inventory: 9, isDefault: true },
    ],
  },
  {
    sku: "SPC-008",
    slug: "oliver-peoples-cat-eye-vintage-sunglasses",
    name: "Vintage Sculpted Cat-Eye Sunglasses Amber",
    categorySlug: "spectacles",
    brandSlug: "oliver-peoples",
    shortDescription: "Gracefully upswept cat-eye sunglasses in rich amber acetate.",
    description: "1960s Riviera inspired feminine cat-eye silhouette with brown gradient UV400 lenses.",
    basePrice: 290.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Vintage Sculpted Cat-Eye", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "Bevelled Italian Acetate" },
    ],
    variants: [
      { sku: "SPC-008-CAT-STD", sizeCode: "STD", colorName: "Tortoise Amber", price: 290.0, inventory: 6, isDefault: true },
    ],
  },
  {
    sku: "SPC-009",
    slug: "cura-geometric-octagonal-wire-frames",
    name: "Octagonal Geometric Titanium Wire Frames",
    categorySlug: "spectacles",
    brandSlug: "cura-atelier",
    shortDescription: "8-sided geometric thin wire optical frame.",
    description: "Modern architectural octagonal geometry forged from Japanese beta-titanium with filigree rim engraving.",
    basePrice: 170.0,
    isFeatured: true,
    isNew: true,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Octagonal Geometric Titanium Wire", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Optical Frames" },
      { name: "frameMaterial", value: "Japanese Titanium Wire" },
    ],
    variants: [
      { sku: "SPC-009-OCT-STD", sizeCode: "STD", colorName: "Metallic Silver", price: 170.0, inventory: 14, isDefault: true },
    ],
  },
  {
    sku: "SPC-010",
    slug: "visionary-flat-top-shield-sunglasses",
    name: "Flat-Top Monolith Shield Sunglasses Matte Black",
    categorySlug: "spectacles",
    brandSlug: "visionary-frames",
    shortDescription: "Futuristic flat-top straight bridge shield sunglasses.",
    description: "Single-piece continuous dark lens mounted into a precision matte black polyamide frame.",
    basePrice: 195.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Flat-Top Monolith Shield Sunglasses", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "TR90 Polyamide" },
    ],
    variants: [
      { sku: "SPC-010-SHL-STD", sizeCode: "STD", colorName: "Matte Black", price: 195.0, inventory: 11, isDefault: true },
    ],
  },
  {
    sku: "SPC-011",
    slug: "cura-rimless-titanium-optical-spectacles",
    name: "Ultra-Light Rimless Titanium Optical Spectacles",
    categorySlug: "spectacles",
    brandSlug: "cura-atelier",
    shortDescription: "Frameless minimal optical glasses weighing only 7 grams.",
    description: "Barely-there rimless optics with flexible titanium tension temples and silicone nose bridge mountings.",
    basePrice: 180.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Ultra-Light Rimless Titanium", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Optical Frames" },
      { name: "frameMaterial", value: "Flex Titanium" },
    ],
    variants: [
      { sku: "SPC-011-RML-STD", sizeCode: "STD", colorName: "Metallic Silver", price: 180.0, inventory: 16, isDefault: true },
    ],
  },
  {
    sku: "SPC-012",
    slug: "moscot-rounded-p3-acetate-glasses-olive",
    name: "P3 Rounded Acetate Spectacles Olive Crystal",
    categorySlug: "spectacles",
    brandSlug: "moscot-studio",
    shortDescription: "Vintage P3 pantoscopic angle rounded optical frame.",
    description: "Classic P3 shape in translucent olive crystal acetate with signature dot rivets and comfortable saddle bridge.",
    basePrice: 205.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "P3 Rounded Acetate Spectacles", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Optical Frames" },
      { name: "frameMaterial", value: "Translucent Olive Acetate" },
    ],
    variants: [
      { sku: "SPC-012-P3-STD", sizeCode: "STD", colorName: "Olive Green", price: 205.0, inventory: 8, isDefault: true },
    ],
  },
  {
    sku: "SPC-013",
    slug: "visionary-clip-on-magnetic-solar-glasses",
    name: "Optical Frame with Magnetic Polarized Solar Clip",
    categorySlug: "spectacles",
    brandSlug: "visionary-frames",
    shortDescription: "2-in-1 optical frame with instant magnetic polarized clip-on.",
    description: "Seamless transition from prescription glasses to polarized sunglasses via subtle hidden neodymium magnets.",
    basePrice: 230.0,
    isFeatured: true,
    isNew: true,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Optical Frame with Magnetic Clip", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "Ultem & Titanium Clip" },
      { name: "badge", value: "NEW DROP" },
    ],
    variants: [
      { sku: "SPC-013-CLP-STD", sizeCode: "STD", colorName: "Monochrome Black", price: 230.0, inventory: 13, isDefault: true },
    ],
  },
  {
    sku: "SPC-014",
    slug: "cura-blue-light-blocking-square-transparent",
    name: "Clear Square Blue-Light Screen Glasses",
    categorySlug: "spectacles",
    brandSlug: "cura-atelier",
    shortDescription: "Clear acrylic square frames with anti-glare blue light lenses.",
    description: "Protects against 99% of harmful high-energy visible (HEV) blue light emitted by monitors and smartphones.",
    basePrice: 85.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Clear Square Blue-Light Glasses", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Anti-Blue Light" },
      { name: "frameMaterial", value: "TR90 Clear Acrylic" },
    ],
    variants: [
      { sku: "SPC-014-CLR-STD", sizeCode: "STD", colorName: "Crystal Clear", price: 85.0, inventory: 25, isDefault: true },
    ],
  },
  {
    sku: "SPC-015",
    slug: "oliver-peoples-flip-up-round-sunglasses",
    name: "Architectural Flip-Up Round Sunglasses",
    categorySlug: "spectacles",
    brandSlug: "oliver-peoples",
    shortDescription: "Double-ring round frame with flip-up sun lenses.",
    description: "Collector's edition dual-frame construction allowing instant flip-up operation between tinted and clear lenses.",
    basePrice: 340.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Flip-Up Round Sunglasses", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "Japanese Titanium & Acetate" },
    ],
    variants: [
      { sku: "SPC-015-FLP-STD", sizeCode: "STD", colorName: "Tortoise Amber", price: 340.0, inventory: 3, isDefault: true },
    ],
  },
  {
    sku: "SPC-016",
    slug: "cura-matte-black-oversized-square-solar",
    name: "Oversized Monolith Square Sunglasses Black",
    categorySlug: "spectacles",
    brandSlug: "cura-atelier",
    shortDescription: "Substantial dark lens statement square sunglasses.",
    description: "Bold full-coverage square acetate sunglasses featuring dark grey Category 3 UV400 lenses.",
    basePrice: 150.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Oversized Monolith Square Sunglasses", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "Bio-Based Acetate" },
    ],
    variants: [
      { sku: "SPC-016-OVR-STD", sizeCode: "STD", colorName: "Monochrome Black", price: 150.0, inventory: 17, isDefault: true },
    ],
  },
  {
    sku: "SPC-017",
    slug: "visionary-clubmaster-browline-spectacles",
    name: "Browline Clubmaster Spectacles Black & Gold",
    categorySlug: "spectacles",
    brandSlug: "visionary-frames",
    shortDescription: "1950s browline optical frame with gold wire rim.",
    description: "Upper acetate browline accent combined with gold-plated metal lower lens wire rim.",
    basePrice: 175.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Browline Clubmaster Spectacles", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Optical Frames" },
      { name: "frameMaterial", value: "Combination Acetate & Metal" },
    ],
    variants: [
      { sku: "SPC-017-CLB-STD", sizeCode: "STD", colorName: "Monochrome Black", price: 175.0, inventory: 12, isDefault: true },
    ],
  },
  {
    sku: "SPC-018",
    slug: "cura-photochromic-transition-reading-glasses",
    name: "Photochromic Transition Smart Reading Glasses",
    categorySlug: "spectacles",
    brandSlug: "cura-atelier",
    shortDescription: "Lenses that automatically darken in outdoor sunlight.",
    description: "Smart optical lenses that remain clear indoors and automatically transition to dark sunglasses when exposed to UV light.",
    basePrice: 160.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Photochromic Transition Smart Glasses", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Anti-Blue Light" },
      { name: "frameMaterial", value: "Lightweight Swiss Grilamid" },
    ],
    variants: [
      { sku: "SPC-018-PHT-STD", sizeCode: "STD", colorName: "Matte Black", price: 160.0, inventory: 19, isDefault: true },
    ],
  },
  {
    sku: "SPC-019",
    slug: "moscot-thin-titanium-pantos-frames",
    name: "Pantos Keyhole Titanium Glasses Rose Gold",
    categorySlug: "spectacles",
    brandSlug: "moscot-studio",
    shortDescription: "Featherlight pantos round titanium optical frame.",
    description: "Finely engraved eyewire pantos silhouette featuring coin-edge bridge detailing and hypoallergenic titanium pads.",
    basePrice: 245.0,
    isFeatured: false,
    isNew: false,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Pantos Keyhole Titanium Glasses", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Optical Frames" },
      { name: "frameMaterial", value: "Japanese Pure Titanium" },
    ],
    variants: [
      { sku: "SPC-019-PNT-STD", sizeCode: "STD", colorName: "Rose Gold", price: 245.0, inventory: 7, isDefault: true },
    ],
  },
  {
    sku: "SPC-020",
    slug: "cura-sports-wrap-polarized-sunglasses",
    name: "Active Wrap-Around Polarized Sport Sunglasses",
    categorySlug: "spectacles",
    brandSlug: "cura-atelier",
    shortDescription: "Ergonomic wrap sunglasses for cycling and outdoors.",
    description: "Curved 8-base wrap geometry providing full peripheral coverage, hydrophobic lens coating, and non-slip rubber temples.",
    basePrice: 125.0,
    isFeatured: true,
    isNew: true,
    images: [
      { url: EYEWEAR_IMAGE, alt: "Active Wrap-Around Polarized Sport", isPrimary: true, order: 1 },
    ],
    attributes: [
      { name: "subCategory", value: "Polarized Solar" },
      { name: "frameMaterial", value: "TR90 Flex Polymer" },
      { name: "badge", value: "IN-HOUSE" },
    ],
    variants: [
      { sku: "SPC-020-WRP-STD", sizeCode: "STD", colorName: "Matte Black", price: 125.0, inventory: 22, isDefault: true },
    ],
  },
];
